#!/bin/bash
# Here do anything needed to install the service
# i.e. apt-get install -y foo  or  bzr branch http://myserver/mycode /srv/webroot
# Make sure this hook exits cleanly and is idempotent, common problems here are
# failing to account for a debconf question on a dependency, or trying to pull
# from github without installing git first.

apt-get install -y apache2
apt-get install -y libapache2-mod-python
apt-get install -y python-pip python-dev build-essential
pip install MySQL-python
dl = "https://github.com/kiran4399/online_judge/online_judge.tar.gz"
# this is the link to the oj tar fileu
juju-log "Fetching $dl"
wget "$dl" -O /tmp/online_judge.tar.gz   # geting the tar file

juju-log "Extracting online_judge"
tar -xvzf /tmp/online_judge.tar.gz -C /var/www/
# extracting the tar file to a specific location

chmod -R 777 /var/www/html/
# granting all permissions for the html folder in /var/www/

juju-log "Creating apache2 configuration"
cat <<EOF > /etc/apache2/sites-available/000-default.conf
<VirtualHost *:80>
	# The ServerName directive sets the request scheme, hostname and port that
	# the server uses to identify itself. This is used when creating
	# redirection URLs. In the context of virtual hosts, the ServerName
	# specifies what hostname must appear in the request's Host: header to
	# match this virtual host. For the default virtual host (this file) this
	# value is not decisive as it is used as a last resort host regardless.
	# However, you must set it for any further virtual host explicitly.
	#ServerName www.example.com

	ServerAdmin webmaster@localhost
	DocumentRoot /var/www/html

	# Available loglevels: trace8, ..., trace1, debug, info, notice, warn,
	# error, crit, alert, emerg.
	# It is also possible to configure the loglevel for particular
	# modules, e.g.
	#LogLevel info ssl:warn

	ErrorLog ${APACHE_LOG_DIR}/error.log
	CustomLog ${APACHE_LOG_DIR}/access.log combined

    <Directory /var/www/html/>
    AllowOverride All
    Require all granted
    </Directory>
	# For most configuration files from conf-available/, which are
	# enabled or disabled at a global level, it is possible to
	# include a line for only one particular virtual host. For example the
	# following line enables the CGI configuration for this host only
	# after it has been globally disabled with "a2disconf".
	#Include conf-available/serve-cgi-bin.conf
</VirtualHost>

# vim: syntax=apache ts=4 sw=4 sts=4 sr noet
EOF

a2enmod rewrite
#enable a2enmod rewrite
service apache2 restart
#restarting apache2 server. Remember IDEMPOTENCY !!!!
