#!/bin/bash
# Here put anything that is needed to start the service.
# Note that currently this is run directly after install
# i.e. 'service apache2 start'
set -e #If any command fails, stop execution of the hook with that error
service apache2 restart
